### ISSUE TITLE
Use find_package(MPI) instead of setting CC/CXX

### ISSUE THREAD

**Issue by jkelling** [barbagroup/AmgXWrapper#32]
We ran into some trouble building AmgXWrapper on a cluster with an MPI-enabled PETSc, which had primarily the handling of MPI in the AmgXWrapper's cmake.

It uses sets the environment variables `CC` and `CXX` to mpicc if they are not set, possible expecting cmake to pick them up for the CMAKE_*_COMPILER variables:
https://github.com/barbagroup/AmgXWrapper/blob/master/CMakeLists.txt#L17
This behavior is quite unexpected:
* `CC` and `CXX` are usually not set to the mpi compiler wrapper when working in a module environment, but to the actual compiler which should be used.
* Note also, that mpicc, of openmpi at least, checks `CC` and `CXX` itself to figure out which compiler should be wrapped, thus setting them to mpicc would always force the default, which is the compiler mpi was configured with.
* Cmake offers `find_package(MPI)` (optionally add `REQUIRED`), which grabs the required options and libraries from the MPI compiler wrapper to then build using the CMAKE_*_COMPILER. This is what cmake users expect to take place.

## Symptoms of this are:
* The `FindPETSc.cmake` will fail with linker errors if PETSc is build with MPI and `C*` are set in the environment (finding the solution to this takes time because of the unexpected behavior)
* On the cluster we worked on, calling `MPI_Init` when the executable is not run through `mpirun`/`mpiexec` causes SIGPIPE. `find_package(MPI)` will set the variable `MPIEXEC_EXECUTABLE` which could be used, or might automatically be used, by `check_cxx_source_runs` in https://github.com/barbagroup/AmgXWrapper/blob/master/cmake-modules/FindPackageMultipass.cmake#L99 to avoid this issue.

## Complications
* Simply adding `find_package(MPI)` to the `CMakeLists.txt` and setting `CMAKE_EXE_LINKER_FLAGS` to the values provided by it does not work: It appears this variable is overwritten or cleared in some place we did not find.

**Comment by piyueh** [comment]
Thanks for reporting this issue! It's indeed unexpected.

I didn't expect OpenMPI to check `CC` and `CXX` to determine the backend compiler even under module environments. This doesn't seem to follow OpenMPI's design according to its documentation. The [OpenMPI documentation](https://www.open-mpi.org/faq/?category=mpi-apps#override-wrappers-after-v1.0) says OpenMPI checks `OMPI_CC` and `OMPI_CXX` for the backend compilers. And setting `CC` and `CXX` to MPI wrapper is common when compiling MPI-based programs. For example, the official documentation of HDF5 ([here](https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/release_docs/INSTALL_parallel)) suggests setting `CC` to `mpicc`. Some large-scale clusters (like those at national labs) may change this behavior of OpenMPI wrapper to reflect the specialized hardware, but I guess this is not common.

But anyway, relying on `FindMPI` module is indeed a better solution. I don't remember why we end up with forcing `CC` and `CXX` in `CMakeLists.txt`. But it has been several years since we added those lines. So I think we can give `FindMPI` another try. I'm kind of busy this week, so if you are able to fix the issue, a pull request is always welcome!

For the linking problem, I'm not sure `CMAKE_EXE_LINKER_FLAGS` should be directly set in `CMakeLists.txt`. I remember it is a cache variable and so is supposed to be used by users in their cmd arguments. Instead, I think one of the popular ways is to just add linker flags to `TARGET_LINK_LIBRARIES` or `TARGET_LINK_OPTIONS`.

**Comment by jkelling** [comment]
> For the linking problem, I'm not sure `CMAKE_EXE_LINKER_FLAGS` should be directly set in `CMakeLists.txt`. I remember it is a cache variable and so is supposed to be used by users in their cmd arguments. Instead, I think one of the popular ways is to just add linker flags to `TARGET_LINK_LIBRARIES` or `TARGET_LINK_OPTIONS`.

Indeed, it should be set this way.

**Comment by jkelling** [comment]
Will also not have the time to fix it any time soon, especaily since there may be a major issue of getting `check_cxx_source_runs` to use `MPIEXEC_EXECUTABLE`. This is not functionality I am familiar with.

**Comment by piyueh** [comment]
Probably is resolved in pr #35
